// <auto-generated />
using System;
using ArduinoIntegrationApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArduinoIntegrationApi.Migrations
{
    [DbContext(typeof(ArduinoApiContext))]
    [Migration("20211003180241_intial")]
    partial class intial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ArduinoIntegrationApi.DataModels.CurtainReading", b =>
                {
                    b.Property<int>("Cur_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cur_Value")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Cur_Id");

                    b.ToTable("CurtainReading");
                });

            modelBuilder.Entity("ArduinoIntegrationApi.DataModels.HumidityReading", b =>
                {
                    b.Property<int>("Hum_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Hum_Value")
                        .HasColumnType("real");

                    b.HasKey("Hum_Id");

                    b.ToTable("HumidityReading");
                });

            modelBuilder.Entity("ArduinoIntegrationApi.DataModels.LightReading", b =>
                {
                    b.Property<int>("Ls_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ls_Value")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Ls_Id");

                    b.ToTable("LightReading");
                });

            modelBuilder.Entity("ArduinoIntegrationApi.DataModels.RoomReading", b =>
                {
                    b.Property<string>("Rd_RoomName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Rd_Cts")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurtainReadingCur_Id")
                        .HasColumnType("int");

                    b.Property<int?>("FeetTemperatureReadingTs_Id")
                        .HasColumnType("int");

                    b.Property<int?>("HeadTemperatureReadingTs_Id")
                        .HasColumnType("int");

                    b.Property<int?>("HumidityReadingHum_Id")
                        .HasColumnType("int");

                    b.Property<int?>("LightReadingLs_Id")
                        .HasColumnType("int");

                    b.Property<int?>("SoundReadingSr_Id")
                        .HasColumnType("int");

                    b.HasKey("Rd_RoomName", "Rd_Cts");

                    b.HasIndex("CurtainReadingCur_Id");

                    b.HasIndex("FeetTemperatureReadingTs_Id");

                    b.HasIndex("HeadTemperatureReadingTs_Id");

                    b.HasIndex("HumidityReadingHum_Id");

                    b.HasIndex("LightReadingLs_Id");

                    b.HasIndex("SoundReadingSr_Id");

                    b.ToTable("RoomDatas");
                });

            modelBuilder.Entity("ArduinoIntegrationApi.DataModels.SoundReading", b =>
                {
                    b.Property<int>("Sr_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Sr_Value")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Sr_Id");

                    b.ToTable("SoundReading");
                });

            modelBuilder.Entity("ArduinoIntegrationApi.DataModels.TemperatureReading", b =>
                {
                    b.Property<int>("Ts_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Ts_Value")
                        .HasColumnType("real");

                    b.HasKey("Ts_Id");

                    b.ToTable("TemperatureReading");
                });

            modelBuilder.Entity("ArduinoIntegrationApi.DataModels.RoomReading", b =>
                {
                    b.HasOne("ArduinoIntegrationApi.DataModels.CurtainReading", "CurtainReading")
                        .WithMany()
                        .HasForeignKey("CurtainReadingCur_Id");

                    b.HasOne("ArduinoIntegrationApi.DataModels.TemperatureReading", "FeetTemperatureReading")
                        .WithMany()
                        .HasForeignKey("FeetTemperatureReadingTs_Id");

                    b.HasOne("ArduinoIntegrationApi.DataModels.TemperatureReading", "HeadTemperatureReading")
                        .WithMany()
                        .HasForeignKey("HeadTemperatureReadingTs_Id");

                    b.HasOne("ArduinoIntegrationApi.DataModels.HumidityReading", "HumidityReading")
                        .WithMany()
                        .HasForeignKey("HumidityReadingHum_Id");

                    b.HasOne("ArduinoIntegrationApi.DataModels.LightReading", "LightReading")
                        .WithMany()
                        .HasForeignKey("LightReadingLs_Id");

                    b.HasOne("ArduinoIntegrationApi.DataModels.SoundReading", "SoundReading")
                        .WithMany()
                        .HasForeignKey("SoundReadingSr_Id");

                    b.Navigation("CurtainReading");

                    b.Navigation("FeetTemperatureReading");

                    b.Navigation("HeadTemperatureReading");

                    b.Navigation("HumidityReading");

                    b.Navigation("LightReading");

                    b.Navigation("SoundReading");
                });
#pragma warning restore 612, 618
        }
    }
}
