// <auto-generated />
using System;
using ArduinoIntegrationApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArduinoIntegrationApi.Migrations
{
    [DbContext(typeof(ArduinoApiContext))]
    [Migration("20211005073909_tester")]
    partial class tester
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ArduinoIntegrationApi.DataModels.LightReading", b =>
                {
                    b.Property<int>("Ls_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ls_Value")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Ls_Id");

                    b.ToTable("LightReading");
                });

            modelBuilder.Entity("ArduinoIntegrationApi.DataModels.RoomReading", b =>
                {
                    b.Property<string>("Rd_RoomName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Rd_Cts")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HeadTemperatureReadingTs_Id")
                        .HasColumnType("int");

                    b.Property<int?>("LightReadingLs_Id")
                        .HasColumnType("int");

                    b.HasKey("Rd_RoomName", "Rd_Cts");

                    b.HasIndex("HeadTemperatureReadingTs_Id");

                    b.HasIndex("LightReadingLs_Id");

                    b.ToTable("RoomDatas");
                });

            modelBuilder.Entity("ArduinoIntegrationApi.DataModels.TemperatureReading", b =>
                {
                    b.Property<int>("Ts_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Ts_Value")
                        .HasColumnType("real");

                    b.HasKey("Ts_Id");

                    b.ToTable("TemperatureReading");
                });

            modelBuilder.Entity("ArduinoIntegrationApi.DataModels.RoomReading", b =>
                {
                    b.HasOne("ArduinoIntegrationApi.DataModels.TemperatureReading", "HeadTemperatureReading")
                        .WithMany()
                        .HasForeignKey("HeadTemperatureReadingTs_Id");

                    b.HasOne("ArduinoIntegrationApi.DataModels.LightReading", "LightReading")
                        .WithMany()
                        .HasForeignKey("LightReadingLs_Id");

                    b.Navigation("HeadTemperatureReading");

                    b.Navigation("LightReading");
                });
#pragma warning restore 612, 618
        }
    }
}
